name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.8'
          channel: 'stable'
      - run: flutter --version
#       - run: flutter pub get
      - run: flutter build apk
      
  create-release:
    if: "contains(github.event.head_commit.message, 'release: ')"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.8'
          channel: 'stable'
      - run: flutter build apk
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/app/outputs/flutter-apk/app-release.apk
          asset_name: advella_${{ github.ref }}.apk
          tag: ${{ github.ref }}
          overwrite: true
          body: "Creating a release"

        
        
        
